# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c600b44e1219186087f172faea9f713040f08510615cfedbb01a9ea8347ac5b98ad848b3915619d231bbf8541afe6cc35b86397d84c0089d2c39f9999ca4d5

test:
  secret_key_base: d87ad9fcad2cb6415fa87da169fd75aaaf07decf48765f3177b1121e6f7c339f740f8460333627f45a7eb89ad662229f42d75d0b7ef4713c1f981bd45bc83079

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
